spring:
  application:
    name: eureka-server
server:  port: 8070    
    
eureka:  client:    fetch-registry: false
    register-with-eureka: false
    service-url:      defaultZone: http://localhost:8070/eureka
  server:    wait-time-in-ms-when-sync-empty: 0
    
    
zuul:  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8400              